services:
  frontend:
    image: nginx:alpine
    ports:
      - '8000:80'
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - API_URL=http://backend:8000
    networks:
      - project_network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '8000'
    networks:
      - project_network

networks:
  project_network:
    driver: bridge
