# Generated by Django 5.0.4 on 2025-05-28 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handbook', '0001_initial'),
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.CharField(max_length=100)),
                ('operating_time', models.PositiveIntegerField()),
                ('failure_description', models.TextField()),
                ('spare_parts_used', models.TextField()),
                ('recovery_date', models.CharField(max_length=100)),
                ('downtime', models.CharField(max_length=100)),
                ('failure_node', models.ForeignKey(limit_choices_to={'type': 'FailureNode'}, on_delete=django.db.models.deletion.CASCADE, related_name='failure_node', to='handbook.handbookmodel')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine')),
                ('recovery_method', models.ForeignKey(limit_choices_to={'type': 'RecoveryMethod'}, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_method', to='handbook.handbookmodel')),
                ('service_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
