# Generated by Django 5.0.4 on 2025-05-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HandbookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MachineModel', 'Модель техники'), ('EngineModel', 'Модель двигателя'), ('TransmissionModel', 'Модель трансмиссии'), ('DrivingAxleModel', 'Модель ведущего моста'), ('SteeringAxleModel', 'Модель управляемого моста'), ('MaintenanceType', 'Вид ТО'), ('FailureNode', 'Узел отказа'), ('RecoveryMethod', 'Способ восстановления')], default='MachineModel', max_length=17)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
