# Generated by Django 5.0.4 on 2025-05-28 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handbook', '0001_initial'),
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('operating_time', models.PositiveIntegerField()),
                ('order_number', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine')),
                ('maintenance_type', models.ForeignKey(limit_choices_to={'type': 'MaintenanceType'}, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_type', to='handbook.handbookmodel')),
                ('service_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
