# Generated by Django 5.0.4 on 2025-05-28 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number_machine', models.CharField(max_length=100, unique=True)),
                ('serial_number_engine', models.CharField(max_length=100, unique=True)),
                ('serial_number_transmission', models.CharField(max_length=100, unique=True)),
                ('serial_number_driving_axle', models.CharField(max_length=100, unique=True)),
                ('serial_number_steering_axle', models.CharField(max_length=100, unique=True)),
                ('supply_contract', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('shipment_date_factory', models.DateField(blank=True, null=True)),
                ('consignee', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('equipment_options', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_machines', to=settings.AUTH_USER_MODEL)),
                ('driving_axle_model', models.ForeignKey(limit_choices_to={'type': 'DrivingAxleModel'}, on_delete=django.db.models.deletion.CASCADE, related_name='driving_axle_model', to='handbook.handbookmodel')),
                ('engine_model', models.ForeignKey(limit_choices_to={'type': 'EngineModel'}, on_delete=django.db.models.deletion.CASCADE, related_name='engine_model', to='handbook.handbookmodel')),
                ('machine_model', models.ForeignKey(limit_choices_to={'type': 'MachineModel'}, on_delete=django.db.models.deletion.CASCADE, related_name='machine_model', to='handbook.handbookmodel')),
                ('service_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('steering_axle_model', models.ForeignKey(limit_choices_to={'type': 'SteeringAxleModel'}, on_delete=django.db.models.deletion.CASCADE, related_name='steering_axle_model', to='handbook.handbookmodel')),
                ('transmission_model', models.ForeignKey(limit_choices_to={'type': 'TransmissionModel'}, on_delete=django.db.models.deletion.CASCADE, related_name='transmission_model', to='handbook.handbookmodel')),
            ],
        ),
    ]
